name: Docker Build and Push

on:
  push:
    branches:
      - '**'

concurrency:
  group: "docker-image"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Log in to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Downcase REPO variable
      run: |
        echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.ref_name }}, ghcr.io/${{ env.REPO }}:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
